#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the first argument:
#           sh fake_sh.sh fake_sh.sh
#       If you have a shell that is not POSIX-compliant, but is POSIX-ish (like
#       'dash'), you can run this script with the _POSIX_VERSION environment
#       variable set:
#           _POSIX_VERSION=1 /path/to/script
#       so that non-POSIX features are disabled.
#
#   (2) This script uses 'uname -o' which is not POSIX. We use 'uname -o'
#       only to check for 'Msys' because 'uname -o' is supported there.
#       Using 'uname -o' elsewhere will likely print a non-useful error
#       message and exit, but we only do this check for the Msys case,
#       because Msys is the only known case where we need to force
#       enabling of "sh" in the 'mingw64' shell (actually, we only need
#       this for versions of Msys before 2017-01-01, so this check is
#       only for safety.)
#
#   (3) This script uses Gradle's "gradle" wrapper script, which means
#       this script is just a wrapper for "gradle".  The actual Gradle
#       command is stored in a JAR file in the Gradle distribution.
#

##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*" >&2
}

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # not a param
              */*)  true;;                              # contains a slash
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `$@`.
        args="$args $arg"
    done
fi

# Collect the arguments in the original order.
set -- "$@" "$@"  # hack to work around a bug in some versions of dash: we duplicate
                  # the last argument, but we need to restore the order, so we shift.

# POSIX-compliant version of the 'shift' builtin, which does not support the
# 'shift' command if the number of arguments is zero.  We can't use the
# `if shift` form of condition checking because that is also not POSIX.
if test $# -gt 0; then
    shift
fi

# The execution of the `eval` below sets the shell arguments to whatever is
# in the positional parameters (including arguments without a leading '-')
# after having stripped the leading '-' if the argument has no '=' sign.
# This is used as a workaround for not being able to use 'set -- "${args[@]}"'
# in POSIX shells because it will break if there are more than 1 args because
# the args in the command line will be interpreted as a single argument
# to the 'set' command.
#
# Note: POSIX-compliant shells will never have more than 1 argument after
# stripping at the end of this function because all the arguments are passed
# in a single array via `$@` to `eval` (unless the arguments are quoted, but
# then the positional parameters will be quoted, and the last argument will
# not be stripped in that case).
#
# Also note: we cannot unset the args because 'set --' does not work in POSIX
# if there are 0 args. So we must always have at least one argument.
# shellcheck disable=SC2016
eval 'set -- '"$args"

# Collect the arguments in the original order.
set -- $(printf '%s\n' "$@" | tac)

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot use ${JAVA_OPTS} nor can they use environment variables as arguments.
#     However, we will allow both JAVA_OPTS and GRADLE_OPTS to be set from the environment
#     and we will pass them as-is. We also allow setting them from the build.gradle file's
#     'gradle' task, but we have not implemented that feature.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a pipe or dollar sign to allow the command to work.
# In POSIX `sed` we must use an unquoted string for the substitution, and
# unquoted string require us to escape all special characters. We also must
# escape any backslash in the string for POSIX `sed`.
#
# The following `sed` command removes the outer double quotes from each
# argument and also escapes any character that might be a pipe or dollar sign
# for `xargs`.
#
# The `eval` is needed to expand the variables because POSIX `xargs` will not
# expand them by default.
#
# The `sed` command must be the last instruction before `xargs`, but we cannot
# pipe directly to `xargs` because `xargs` is not a POSIX command. So we must
# use `eval` to execute `xargs` as a command.
#
# The `xargs` command reads from standard input (which in POSIX is the pipe
# from the previous command, but that may not be connected to our stdin; it
# could be connected to a file descriptor from the parent process, e.g. a
# pipe used for process substitution).
eval "printf '%s\n' \"\$@\" | sed 's/\"//g; s/[|$\\]/\\\\&/g' | xargs -n1"

# Finally, execute the command.
exec "$JAVACMD" "$@"
